services:
  # 1. ML Engine (Python)
  - type: web
    name: skillmatch-ml
    env: python
    region: ohio
    plan: free
    rootDir: ml_engine
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: HF_API_TOKEN
        sync: false # Recommended for higher rate limits

  # 3. Backend (Java/Spring Boot via Docker)
  - type: web
    name: skillmatch-backend
    env: docker
    region: ohio
    plan: free
    dockerContext: backend/SkillMatch
    dockerfilePath: Dockerfile
    healthCheckPath: /api/jobs/external
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://ep-lucky-tooth-ag8q522u-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require"
      - key: SPRING_DATASOURCE_USERNAME
        value: "neondb_owner"
      - key: SPRING_DATASOURCE_PASSWORD
        value: "npg_p1TULS4juAeJ"
      - key: ML_ENGINE_URL
        value: https://skillmatch-ml.onrender.com/recommend
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true

  # 4. Frontend (React Static Site)
  - type: web
    name: skillmatch-frontend
    env: static
    region: ohio
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        value: https://skillmatch-backend.onrender.com
